name: Start build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    name: build all project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install g++ cmake libgtest-dev

      - name: Build project
        run: |
          make
          make clean
